### Obtengo todos los libros SQL
GET http://127.0.0.1:3000/api/libros HTTP/1.1

### Creo un nuevo libro SQL
POST http://127.0.0.1:3000/api/libros HTTP/1.1
Content-Type: application/json

{
  "Titulo": "Largo pétalo de mar",
  "IdAutor": 2,
  "FechaPublicacion": "2019-05-01",
  "Genero": "Ficción histórica",
  "Disponibilidad": 1
}

### Modifico disponibilidad del libro mediante su ID SQL
PUT http://127.0.0.1:3000/api/libros/disponibilidad/7 HTTP/1.1
Content-Type: application/json

{
  "Disponibilidad": 1
}

### Obtener todos los libros de un autor por (IdAutor) y la informacion del mismo.
GET http://127.0.0.1:3000/api/libros/autor/5 HTTP/1.1

### Modifico un libro mediante su ID
PUT http://127.0.0.1:3000/api/libros/2 HTTP/1.1
Content-Type: application/json

{
  "Titulo": "Paula",
  "IdAutor": 2,
  "FechaPublicacion": "1994-01-01",
  "Genero": "Autobiografía",
  "Disponibilidad": 1
}












