### Obtengo todos los libros de la biblioteca
GET http://127.0.0.1:3000/api/libros HTTP/1.1

### Obtengo libro por id
GET http://127.0.0.1:3000/api/libros/4 HTTP/1.1

### Publico un nuevo libro
POST http://127.0.0.1:3000/api/libros HTTP/1.1
Content-Type: application/json

{
  "Titulo": "Cuentos de lo grotesco y arabesco",
  "IdAutor": 7,
  "FechaPublicacion": "1840-12-01",
  "Genero": "Terror",
  "Disponibilidad": 1
}



### Modifico un libro por id
PUT http://127.0.0.1:3000/api/libros/40 HTTP/1.1
Content-Type: application/json

{
  "id_libro": 11,
  "titulo": "Indias Blancas",
  "año_publicacion": 2005,
  "genero": "Ficción histórica",
  "id_autor": 11
}





